/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Select an image to display inside the content box, at the top
 */
export type ImageSource = string;
/**
 * Topic for the content box. Displayed before the text, in bold
 */
export type Topic = string;
/**
 * Text for the content box
 */
export type TextContent = string;
export type Inverted = boolean;
export type Headline = string;
/**
 * Add additional css classes that should be applied to the section
 */
export type AdditionalClass = string;

export interface SectionProps {
  width?: "full" | "max" | "wide" | "default" | "narrow";
  gutter?: "large" | "default" | "small" | "none";
  mode?: "default" | "tile" | "list";
  content?: ContentBox[];
  background?: "default" | "accent";
  inverted?: Inverted;
  spaceBefore?: "default" | "small" | "none";
  spaceAfter?: "default" | "small" | "none";
  headline?: Headline;
  className?: AdditionalClass;
  [k: string]: unknown;
}
/**
 * Component to display content in a condensed, boxed form
 */
export interface ContentBox {
  image?: ImageSource;
  topic?: Topic;
  text?: TextContent;
}
