/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `yarn run schema` to regenerate this file.
 */

/**
 * Text content of headline
 */
export type Text = string;
/**
 * Subheadline content
 */
export type Sub = string;
/**
 * Switch order of headline and subheadline
 */
export type SwitchOrder = boolean;
/**
 * Level of headline to use
 */
export type Level = "h1" | "h2" | "h3" | "h4" | "p";
/**
 * Style of headline to show
 */
export type Style = "h1" | "h2" | "h3" | "h4" | "p";
/**
 * Whether to display space after headline
 */
export type SpaceAfter = "minimum" | "small" | "large";

/**
 * Component used for headlines
 */
export interface HeadlineProps {
  text: Text;
  sub?: Sub;
  switchOrder?: SwitchOrder;
  level: Level;
  style?: Style;
  spaceAfter?: SpaceAfter;
  [k: string]: unknown;
}
